### ISSUE TITLE
Unable to upload tracks

### ISSUE THREAD

**Issue by peng90** [gavinbenda/platinum-md#1]
Unable to convert and upload mp3 files to my MZ-N10 with either SP or LP2 quality. The debug console says things like "process ended with code null", "processes ended with code 1" and "process ended with code 0". There's an empty `pmd-temp` created in the same folder of the mp3 file after attempting to upload the mp3 file. Doesn't seem like the app is converting the file from mp3 to ATRAC... 

I've tried with both a blank disk and a disk with other recordings. The app has no problem reading or even deleting the pre-existing recordings.

Any other way to get a better log to figure out what's going on?

**Comment by peng90** [comment]
Some other update:
I was able to upload a track with SP quality using the `netmdcli` that was bundled in the `/resources/mac/bin/` folder. The track is a wav file I converted from a 320 kbps mp3 file following the instructions in linux-minidisc's documentation.
I guess this at least proves the `netmdcli` in the bundle works correctly...

**Comment by gavinbenda** [comment]
Better error reporting and debugging is on the list of improvements, as you've found, it's not overly verbose at the moment! There is one bug I've found where the filename/info may not be properly escaped. But it should generate thee temp files within the `pmd-temp` folder - can you check ffmpeg is working correctly by just typing `ffmpeg` on the commandline and double check your system can find it?

**Comment by peng90** [comment]
`ffmpeg` works since I converted the mp3 file to wav using it... I'll find some time to try to build and run from source to see what's going on. I've never used Vue so I may need some time to learn more about it.

**Comment by peng90** [comment]
Hey just wanna give you an update... I'm a bit under the weather but I'll get back trying to figure out this issue when I'm better.

**Comment by gavinbenda** [comment]
Got a new release 0.2.2 - could you go into settings, open the debug window, and let me know what error you get? Hope you're feeling better!

**Comment by peng90** [comment]
Thanks for asking :] I'm much better.

I just tried the latest release, I'm stuck at the log `Staring WAV conversion process using ffmpeg`. I can see the `pmd-temp` folder being created but nothing happens afterwards.

I can look into it more this weekend to see if `child_process` triggered any other event on `ffmpeg`.

**Comment by peng90** [comment]
Hey I found the problem!

`ffmpeg` exited on SIGABRT because for some reason the `ffmpeg` bundled in the app doesn't work on my machine. I got the error below when I try to do `./ffmpeg -y -i ~/Developer/Platinum-MD-TEST/test.mp3 ~/Developer/Platinum-MD-TEST/test.raw.wav`:

```
dyld: Library not loaded: /usr/local/Cellar/ffmpeg/4.1.4_1/lib/libavdevice.58.dylib
  Referenced from: /Users/xiepeng/Developer/platinum-md/resources/mac/bin/./ffmpeg
  Reason: image not found
fish: './ffmpeg -i ~/Desktop/Platinum-…' terminated by signal SIGABRT (Abort)
```

Also, I tried the same in `bash`, got the same error. Ruled out `fish` is not causing any problem.
The `ffmpeg` I install through `homebrew` works with the same command.

**Comment by peng90** [comment]
Okay.... turned out my ffmpeg was out of date. After running `brew upgrade ffmpeg` everything works now :] I'm closing this issue.

**Comment by gavinbenda** [comment]
Thanks for digging deeper and good to hear it's working!
I'm actually going to replace ffmpeg with the "official" nodejs version, will make it way easier to support other OS's too.

**Comment by peng90** [comment]
Sounds good! I’ll be happy to help testing :)
