### ISSUE TITLE
Won´t show tracks

### ISSUE THREAD

**Issue by digitalsomtum** [gavinbenda/platinum-md#12]
Hi. 
Platinum-md seems to access my MZ-N510 as it can read and write the MD title but says " 0 tracks on NET MD Walkman" despite there being tracks on it. Any suggestions on how to fix this? Thanks in adance!

**Comment by gavinbenda** [comment]
Haven't tested with a N510 - but should work, can you click `Settings` and `Debug Window` and see if there's any interesting errors?

**Comment by digitalsomtum** [comment]
![Screenshot 2020-02-01 at 20 11 32](https://user-images.githubusercontent.com/57040743/73597708-1ec18580-452f-11ea-801d-8b5e1909ae26.png)

**Comment by gavinbenda** [comment]
Do these tracks happen to be in a "group" ?

**Comment by gavinbenda** [comment]
New release should fix this if you want to give it a go.

**Comment by digitalsomtum** [comment]
Great, tried it and now it works. Thanks a lot for putting in the effort!
