### ISSUE TITLE
Chinese characters is supported on PC but not supported on MD, can you support it!

### ISSUE THREAD

**Issue by gongfurong** [gavinbenda/platinum-md#126]
![WechatIMG6](https://user-images.githubusercontent.com/12220924/130187132-938c97c8-51cd-4b94-8cbb-3d5276378d90.png)

**Comment by deenine** [comment]
Are Chinese characters supported by minidisc devices?

**Comment by gavinbenda** [comment]
Yep - think unfortunately the MD devices themselves may not support Chinese characters (unless they work in Sonic Stage?).
