### ISSUE TITLE
Debug window shows: "Cannot read property `substring` of undefined" when loading certain audio files

### ISSUE THREAD

**Issue by justfinish** [gavinbenda/platinum-md#13]
<img width="500" alt="Screen Shot 2020-03-10 at 9 17 45 PM" src="https://user-images.githubusercontent.com/228499/76372699-a3fd3e80-6314-11ea-8583-93c589be05de.png">

Tried converting the audio file, in this case, an FLAC, into WAV and MP3 but didn't help at all. Removing all metadata/attributes from the file didn't help either.

Example audio file: https://drive.google.com/open?id=1XRc2OIJlsjjV3hVRxp92G_L9MQ0_aRjn

**Comment by gavinbenda** [comment]
Just requested access to that file, it might be a string-reading issue - and hopefully easy to sort out.

**Comment by gavinbenda** [comment]
Just pushed version 0.2.5 that should fix this!

**Comment by justfinish** [comment]
Thanks for the fix! Will give it a test shortly!
