### ISSUE TITLE
transfers files over to net md mz-nh900 with success no errors  but then disc says it's blank

### ISSUE THREAD

**Issue by chefdb** [gavinbenda/platinum-md#16]
my player is a MZ-NH900 it is a hi-md md recorder player.   is this device supported?

i have transferred over a series of mp3s over to the net md walkman and i get no errors on debug screen,  all smooth sailing the files all show as transferred  on the minidisc..
 whenI then  unplug from usb and attempt to play the disc it says its blank and when i replug to usb and rescan with platinum md  the disc shows on screen  as blank with no files.   not sure what's happening here 
<img width="1410" alt="Screen Shot 2020-03-18 at 3 05 45 PM" src="https://user-images.githubusercontent.com/61116252/77011861-fac4d280-6929-11ea-88d3-1ae8e85f9f75.png">

**Comment by gavinbenda** [comment]
Just tried with a MZ-NH700 which is pretty close to yours, and had no problems.
The track listing in your screenshot shows that Platinum-MD was successful in transferring the track (it's impossible to get that info without it coming from the MD player itself).

I wonder if there's something up with the recorder, i.e. not writing the TOC properly after it's finished... before disconnecting from USB, are you pressing the stop button on the player?

**Comment by chefdb** [comment]
could it be a bad write head?  i just purchased the unit off eBay.. so this is the first time i am using it.. scouring internet for ideas what’s happening many point to a bad write head.. would the debug window tell me that?

**Comment by gavinbenda** [comment]
The debug window 100% confirms that the recorder is successfully writing a track to the player.
Next time you try, transfer a song, and **BEFORE** unplugging the USB cord, press the physical 'stop' button on the device and ensure you see the device screen confirm "Writing System Files" and then the screen will also confirm that it's ok to eject the disc.

**Comment by chefdb** [comment]
yes i pressed stop and waited for the device to say eject disc ok. 

its just confusing because the app shows the songs as being transferred in the right window and the time left on the disc is accurate .. but then when i eject and put it back in its all gone..

**Comment by chefdb** [comment]
yes  i did that .. and it said rising system files on the unit and then ok to eject..   but as soon as put it back in to the unit and  i also tried it on a minds rack deck that also reads as blank

**Comment by chefdb** [comment]
*writing system files

**Comment by gavinbenda** [comment]
I would say unfortunately it's a hardware error in that case. Have you tried recording in other ways like line-in?

**Comment by chefdb** [comment]
yea   same result..  ..i  get a blank disc after i unplug from the line in which i recorded a few minutes of  screen on unit shows the audio is coming in and writing to disc.. its weird it shows me no error.. .. ah well.. i think i need to try and return on eBay . :(  was looking forward to transferring the songs over!   maybe next one will work..

**Comment by gavinbenda** [comment]
Sorry to hear - yep certainly sounds like something isn't right with the hardware :(
