### ISSUE TITLE
Does the type-S chipset is used when transferring in SP mode?

### ISSUE THREAD

**Issue by jialrs** [gavinbenda/platinum-md#166]
Hi, I like platinum-md very much! But I have a question about the type-S chipset.
My NE810 supports Type-S. As far as I know, Type-S is compatible with Type-R, which can greatly improve the sound quality of SP. This chip works when recording through digital optical recording. 
I wonder if this chip still works when using platinum-md's SP mode. If so, then I can ditch fiber-optic recording altogether.

Thanks!

**Comment by gavinbenda** [comment]
Hi there! Type-S should contain all of the Type-R improvements (plus the LP2 playback improvements that Type-S also brings).

**Comment by jialrs** [comment]
> Hi there! Type-S should contain all of the Type-R improvements (plus the LP2 playback improvements that Type-S also brings).

Thanks for reply! So I am wondering if I record music through platinum-md and PC, instead of digital optical, does the type-S also works to improve the quality of music? Someone says that the type-s not work when transferring music with SonicStage and PC.

**Comment by gavinbenda** [comment]
With SonicStage, SP files are actually just LP2 files in an SP "compatible" wrapper, so you will only ever have LP2 quality, and they are encoded with SonicStage, then sent to the MD player.

With the method that we are using, the direct/raw PCM/WAV file is sent to the player, and the encoding happens on the device itself.

Edit: Type-S enhancements were mainly for playback of LP2 files, not for SP, but all Type-R enhancements are within Type-S as it's newer.

**Comment by jialrs** [comment]
> With SonicStage, SP files are actually just LP2 files in an SP "compatible" wrapper, so you will only ever have LP2 quality, and they are encoded with SonicStage, then sent to the MD player.
> 
> With the method that we are using, the direct/raw PCM/WAV file is sent to the player, and the encoding happens on the device itself.
> 
> Edit: Type-S enhancements were mainly for playback of LP2 files, not for SP, but all Type-R enhancements are within Type-S as it's newer.

Thanks a lot! So I can understand that with your method (in SP mode), the recording effect is the same as with fiber optic recording effect (also in SP mode)?

**Comment by maverickmatt** [comment]
> 

Yes. The device is doing the encoding with both methods in SP

**Comment by jialrs** [comment]
> > 
> 
> Yes. The device is doing the encoding with both methods in SP

Thanks a lot! I get the answer and close this issue.
