### ISSUE TITLE
CLI did not return valid JSON data 

### ISSUE THREAD

**Issue by ukozi** [gavinbenda/platinum-md#167]
Device: Sharp IM-DR80-S
Connecting to: MacBook Pro (M1 Max, macOS Ventura (13.0)

Dependencies all installed according to troubleshooter (attached).
<img width="751" alt="Screenshot 2022-10-16 at 5 52 41 PM" src="https://user-images.githubusercontent.com/3391773/196060018-510313c8-65b5-4a0d-83e8-3ea08dd39430.png">

Player/dock show up in the system profiler and in the "connected usb devices" dialog (attached). 

<img width="736" alt="Screenshot 2022-10-16 at 5 53 05 PM" src="https://user-images.githubusercontent.com/3391773/196060038-3de00a08-d183-4325-b66e-7610ddbde0b1.png">

Of note is that the MD player does NOT get a green highlight like my MZ-RH1 did. However, it will appear as "Negotiating". With the debugger activated, I can see it identifies the device `{locationId: xxxx, vendorID: 1245, productID: 36884, deviceName: "Net MD"...}` and then "No connection" followed by a "Attempting to read from NetMD", before inevitably ending in CLI did not return valid json data:

<img width="834" alt="Screenshot 2022-10-16 at 5 52 12 PM" src="https://user-images.githubusercontent.com/3391773/196059997-8082424d-4d54-4237-8a32-f5464a74ddc9.png">

I have tried using USB hubs and connecting it via an Apple USB-C to USB-A adapter.

**Comment by gavinbenda** [comment]
Just released a new version tested on an M1 - can find it here - https://github.com/gavinbenda/platinum-md/releases/download/v1.2.1/platinum-md-1.2.1-m1.dmg

**Comment by ukozi** [comment]
Resolved with version 1.2.1-m1.
