### ISSUE TITLE
No available formula with the name "pkg-config".

### ISSUE THREAD

**Issue by gjros1** [gavinbenda/platinum-md#168]
Hi there,

I have run into the issue that I cannot download the necessary codecs. See the screenshot for extra information.

Is this just me, and if so, how do I fix this?

GJ
![Screenshot 2022-10-17 at 11 48 02](https://user-images.githubusercontent.com/115987427/196147499-6dfc3cec-ebeb-425b-97d1-b2984897b61e.png)

**Comment by gavinbenda** [comment]
That is a bit strange, did you already have brew installed and maybe need to update it with `brew update` ?

**Comment by gjros1** [comment]
Hi! Thanks for replying. Seemingly my Brew install was incomplete. Should this happen to anyone else: uninstall entirely, including folders, and reinstall. Compliments on the app, it’s worked a charm :)
