### ISSUE TITLE
Can't see list of music in folder (Unexpected end of JSON input) 

### ISSUE THREAD

**Issue by ukozi** [gavinbenda/platinum-md#169]
When selecting a folder of music with presumably supported files (M4A, MP3) nothing shows in the UI. Upon running the debugger, I can see:

`DevTools failed to load source map: Could not parse content for file:///Applications/platinum-md.app/Contents/Resources/app.asar/node_modules/music-metadata/lib/common/RandomFileReader.js.map: Unexpected end of JSON input`

MacOS Ventura (13.0) on an M1 MacBook.

Wish I could be of more help than just opening issues! JS isn't quite my thing, though, so I donated instead.

**Comment by ukozi** [comment]
Something came to my mind earlier and so I attempted to give p-md "Full Disk Access" in the Privacy & Settings pane of the settings app (since I didn't remember the app asking me when I first browsed to the music folder). I added it but it didn't resolve the problem. I'd also like to clarify as I didn't see earlier the errors in the debugger were different. Here's a screenshot after I select a folder to read music from:

<img width="832" alt="Screenshot 2022-10-18 at 8 51 57 PM" src="https://user-images.githubusercontent.com/3391773/196571966-e98c8431-494c-4350-b3fd-2a5019b3d370.png">

<img width="811" alt="Screenshot 2022-10-18 at 8 52 24 PM" src="https://user-images.githubusercontent.com/3391773/196572003-dc14eb3d-850e-4ccf-8d63-a08bfa926551.png">

<img width="848" alt="Screenshot 2022-10-18 at 8 52 46 PM" src="https://user-images.githubusercontent.com/3391773/196572039-f9a9f84d-4aef-439c-a423-5607d41ea07f.png">

**Comment by ukozi** [comment]
<img width="839" alt="Screenshot 2022-10-18 at 9 01 14 PM" src="https://user-images.githubusercontent.com/3391773/196572883-06acd78e-a957-4032-8a9b-47b79d80a9c2.png">

This happens when trying to refresh the tracks listing with the music folder selected. I suppose it could be typical of an empty list to not be iterable, but just in case it's useful.

**Comment by gavinbenda** [comment]
I've got a fix for this - it was due to a small change in the way opening dialog boxes works in electron (now uses a promise, which is good).

I've removed the previous release and added a new hotfix version here:
https://github.com/gavinbenda/platinum-md/releases/download/v1.2.1/platinum-md-1.2.1-m1-hotfix.dmg

> Wish I could be of more help than just opening issues! JS isn't quite my thing, though, so I donated instead.

Thanks very much for this!

**Comment by ukozi** [comment]
> Thanks very much for this!

Back at you for your work on this project!

Issue resolved with hotfix.
