### ISSUE TITLE
Limited codec support despite using FFmpeg

### ISSUE THREAD

**Issue by ticky** [gavinbenda/platinum-md#20]
FFmpeg is capable of decoding a lot more [than WAV, MP3 and FLAC](https://github.com/gavinbenda/platinum-md/blob/e47afb1555c90f2de27a2be5c9d805d4bc583437/src/renderer/components/LandingPage/DirectoryListing.vue#L167). It would be great for platinum-md to handle other codecs as well.

`music-metadata` likewise supports many, many formats, so even things like AAC, ALAC, APE, DSD, OGG and WMA would work with just removing this restriction.

If you wanted to be really, really correct about this, a way to still filter what files you scan with `music-metadata` might be to populate your list of accepted file extensions using the output of `ffmpeg -demuxers`, which lists, in the second column, the file extension or extensions, of these formats (significantly trimmed down for clarity):

```
File formats:
 D. = Demuxing supported
 .E = Muxing supported
 --
 D  aac             raw ADTS AAC (Advanced Audio Coding)
 D  ac3             raw AC-3
 D  aiff            Audio IFF
 D  alaw            PCM A-law
 D  ape             Monkey's Audio
 D  asf             ASF (Advanced / Active Streaming Format)
 D  caf             Apple CAF (Core Audio Format)
 D  dts             raw DTS
 D  dtshd           raw DTS-HD
 D  f32be           PCM 32-bit floating-point big-endian
 D  f32le           PCM 32-bit floating-point little-endian
 D  f64be           PCM 64-bit floating-point big-endian
 D  f64le           PCM 64-bit floating-point little-endian
 D  flac            raw FLAC
 D  mov,mp4,m4a,3gp,3g2,mj2 QuickTime / MOV
 D  mp3             MP2/3 (MPEG audio layer 2/3)
 D  ogg             Ogg
 D  oma             Sony OpenMG audio
 D  wv              WavPack
```

**Comment by gavinbenda** [comment]
Happy to add a whole bunch more in - have only added formats that I've tested so far.
Also need to refactor that code a little.

**Comment by Invictaz** [comment]
@ticky could you also implement this fix? 
https://github.com/dcherednik/atracdenc/issues/9#issuecomment-570356624

So that ATRAC3 files can directly be inputted as well to convert them to ATRAC1? 
Platinum-MD uses "atracdenc" as well but not this fix yet I think.

**Comment by gavinbenda** [comment]
Effectively doing the same thing at the moment, as described here:

> You can decode atrac3plus by ffmpeg to pcm and than encode pcm to atrac1. The result will be same.

Because there's no fluent API for atracdenc, it's probably better to keep things as it is, but happy to change if there's specific issues you're coming across at the moment.

You'll be pleased to know in the next release, it cleans up temp files after it's finished.

**Comment by Invictaz** [comment]
@gavinbenda I asked for the issue because the step in between isn't likeable. The only thing I would like to have is ATRAC3 -> ATRAC1.
