### ISSUE TITLE
Impossible to access local file

### ISSUE THREAD

**Issue by YugoDago87** [gavinbenda/platinum-md#26]
Hello,

Thank you for that great work you did.

I face an issue when I want to transfert from my comptuer to my NetMD (MZ-RH1).
Platinium MD does not allow me to select files in the"browser", I mean, files are "shadows" and I can't select them, like missing permission.

Do you know if I have to add Appimage to a specific group ?

Thank you very much.

**Comment by gavinbenda** [comment]
Could you post a screenshot ?

**Comment by YugoDago87** [comment]
Hi,

Here it is.

![image](https://user-images.githubusercontent.com/62613255/77929893-7c155100-72aa-11ea-8133-a503ba271bab.png)

I tried to look at different folder, from the desktop, no change.

The soft them self seems to detect the MD Player and Discs without issue :

![image](https://user-images.githubusercontent.com/62613255/77930100-b7b01b00-72aa-11ea-89e0-81d7021cd26c.png)

**Comment by gavinbenda** [comment]
Because it's a "Folder" selector, you should just be able to click "ok" to select the folder you're in (rather than the files). If that isn't working, try clicking "settings" and "debug window" - you'll see some error messages in there that may help!

**Comment by YugoDago87** [comment]
Thank you for you answer.
Sorry to be stupid ... :-) This is working

**Comment by gavinbenda** [comment]
Great to hear - enjoy!
