### ISSUE TITLE
Enable per file transfer mode

### ISSUE THREAD

**Issue by Invictaz** [gavinbenda/platinum-md#28]
Now transfer mode is a generic setting, so for all files.
It would be cool to be able to change the setting per file. So you can make a mix of LP4 songs and SP on the same disc and then start the transfer.

![image](https://user-images.githubusercontent.com/20338545/78087562-bc1b2780-73c1-11ea-82ee-90a7526ef66e.png)

**Comment by gavinbenda** [comment]
At this stage, I haven't had any other requests for this - but will reconsider again if it becomes a wanted feature, or I have a bunch of time on my hands to implement.
