### ISSUE TITLE
Status Percentage/progress bar.

### ISSUE THREAD

**Issue by Polish-Jack** [gavinbenda/platinum-md#30]
I find that when copying a large audio file to the MiniDisc I can't tell how the transfer is doing or guess how long it will take.  Some sort of percentage or progress bar would be nice.

**Comment by Invictaz** [comment]
Second this, only the debug window now has some sort of progress indication. Sonicstage has a clear percentage overview in the transfer window next to the track that is transferred - 45% or something.

**Comment by gavinbenda** [comment]
Track transfer progress will now display in the next release.

**Comment by maverickmatt** [comment]
Awesome!
