### ISSUE TITLE
Hex/Decimal error playing tracks beyond #10

### ISSUE THREAD

**Issue by maverickmatt** [gavinbenda/platinum-md#33]
When pressing play button next to tracks in track list, track numbers past track 10 (9 internally since the list is 0-based) are playing the wrong track. It appears decimal track number is being treated as hex, so track 11 (10 in json object in console) instead plays track 17 (I may be off by a digit as I'm not at my computer). Behavior is consistent as you continue.

I think I experienced the same base issue renaming tracks on a disc, but I need to gather more info, as it also corrupted the track numbers, so listing shows more tracks than there really are, and some track marks are now in the middle of songs (which incidentally play gapless :) )

**Comment by eRadiofan** [comment]
I think I have run into a variant of this. On a minidisc with only 15 tracks, the play button beyond track 10 effectively plays track 10.

Workaround: The tracks can be reached using the next track button.

**Comment by gavinbenda** [comment]
I've put in the fix mentioned at the linux-minidisc issue report - and it seems to work? Have tested on an MZ-N10 - will be in the next release.

**Comment by eRadiofan** [comment]
Which fork are you using?

**Comment by gavinbenda** [comment]
Maintaining this one, as I need the output from it in JSON
https://github.com/gavinbenda/linux-minidisc
