### ISSUE TITLE
Any plans to include HI-MD coded music?

### ISSUE THREAD

**Issue by Seeker000** [gavinbenda/platinum-md#40]
I'm very excited to see your efforts to keep the minidisc format alive.

Do you have any plans to include the HI-MD format? All of my music is HI-MD.

Thanks in advance.

Kevin Siddons

**Comment by Invictaz** [comment]
Duplicate of #8

**Comment by gavinbenda** [comment]
There is some work being done by the linux-minidisc project on Hi-MD - at the moment there isn't a method to transfer quite yet as it involves some quite niche (and complex) maths around encryption and compression.
