### ISSUE TITLE
Windows: not writing all tracks at once but reset after each track

### ISSUE THREAD

**Issue by Nickelig** [gavinbenda/platinum-md#49]
Hello

I noticed that when I send multiple tracks to be written on the disc, it always writes one track at a time, then somehow it resets for a very brief moment (and my mz n910 as well), reseeks the position and then writes the next track etc... so essentially instead of writing 18 tracks in one sessions, the software writes them in 18 sessions.

This is very worrying for me as our equipment is very old and not getting any younger. My MZ N910 especially is really stressed out when it has to make huge jumps/skips. As it is now, my MZ N910 has to reseek the recording position 17 times if I want to write 18 tracks... instead of continously writing them in one session.

As much as I like Platinum Md and I am so so so glad you guys are doing it, please look into any possibilty to reduce mechanical stress on our old devices. 

I don‘t know if it is an issue with the Windows version or with Linux/Mac as well (I only have Win10), just wanted to mention I witness this behavior when using the Windows version.

**Comment by gavinbenda** [comment]
This is (unless I'm mistaken in my interpretation) just how linux-minidisc works, the TOC is written at the end of each track (the concept of a multi-track 'session' doesn't exist) - it's an interesting point about hardware wear, but unless you're recording hundreds of discs a day, I'm not sure it will make a huge difference in the lifetime of the device unless it already has an existing problem - sounds like you might need a little grease on the worm drive!
