### ISSUE TITLE
anther transfer issue 

### ISSUE THREAD

**Issue by digitalsomtum** [gavinbenda/platinum-md#5]
just addressed the problem with different ffmpeg version and now that seems no longer an issue but encountered a new problem:

![Screenshot 2019-10-26 at 16 49 31](https://user-images.githubusercontent.com/57040743/67621649-be28fb00-f811-11e9-904b-da254b460c3f.png)

**Comment by patchrick84** [comment]
I've gotten that a few times and usually succeeds on the second attempt - which, unfortunately, Platinum MD shows now progress on as of yet.  But the player should show that it's recording, or trying to.

**Comment by digitalsomtum** [comment]
Thanks Patchrick84 for the reply but nothing happens. It is stuck in a look retrying to send the file. Tried three different players and it seems that the send command does not work in my case.

**Comment by gavinbenda** [comment]
What NetMD device are you using?

**Comment by digitalsomtum** [comment]
OK. Interesting, just found out that it works if I send it in LP2 format. Any advice on what might me the issue?

**Comment by digitalsomtum** [comment]
I tried a Mz-N10, a MZ-NH700 and a MZ-N510

**Comment by gavinbenda** [comment]
Is your source file a 96kbps MP3? I'm wondering if there's an issue with the file format being converted to WAV, do you have maybe a WAV file or an MP3 track you can test with to rule that out? I often use an N10 with the app so 100% know that works at least.

**Comment by gavinbenda** [comment]
The other "weird thing" could be the file name title has an "!" in it, you could try removing that to see if that makes a difference (before you transfer).

**Comment by digitalsomtum** [comment]
Thanks Gavin, actually got it to work on my N10. Though I think there is an issue with my unit and not the software.
