### ISSUE TITLE
Enhancement to renaming tracks

### ISSUE THREAD

**Issue by eRadiofan** [gavinbenda/platinum-md#55]
When renaming tracks on a whole MD, it would be much quicker if:

1) The text box is automatically focussed so that one can just start typing
2) Pressing <Enter> submits the change

This saves two mouse clicks per title.

**Comment by eRadiofan** [comment]
I have a small change for this, but I can't push my branch. Do I need to be added as a contributor?

**Comment by gavinbenda** [comment]
Did you manage to get your branch working? You won't be able to push directly to develop/master - but you should be able to make a pull request.

**Comment by eRadiofan** [comment]
I created a branch of develop because the code there looks newer.
My branch works but I can't push it (create branch on the server). Some permissions problem.

**Comment by gavinbenda** [comment]
Most of the new code has been merged into Master now, so perhaps try pulling down that, and adding your code there, and creating the pull request on Master?

**Comment by eRadiofan** [comment]
I can't push the branch, I get this error:

`Can't connect to any URI: https://github.com/gavinbenda/platinum-md.git (https://github.com/gavinbenda/platinum-md.git: git-receive-pack not permitted on 'https://github.com/gavinbenda/platinum-md.git/')`

I've attached the updated file: [NetMdListing.txt](https://github.com/gavinbenda/platinum-md/files/5074869/NetMdListing.txt)

**Comment by gavinbenda** [comment]
It seems like that error might mean your GitHub username/pass aren't registered correctly, or your email on GitHub isn't verified yet? Either way, I'll merge those changes, thank you!

**Comment by eRadiofan** [comment]
I can create a fork but I can't create a branch from the web interface either. I think it must be a project setting.
It would be useful if I could create branches rather than working in my own fork.
