### ISSUE TITLE
Update netmdcli binaries

### ISSUE THREAD

**Issue by andyboeh** [gavinbenda/platinum-md#56]
In https://github.com/vuori/linux-minidisc/pull/8 support for Sharp MiniDisc players was added. Could you update the netmdcli binaries to the latest version?

**Comment by gavinbenda** [comment]
Hey - thanks for this, I actually already added it a [while back](https://github.com/gavinbenda/linux-minidisc/commit/5b78c0cdbee46a15df9e18a02cc34b7f5f86f26e)! Will be doing a new release soon, which will include the new binaries.

**Comment by andyboeh** [comment]
Ah, of course - sorry, looking forward to the new release!

**Comment by Invictaz** [comment]
@gavinbenda can this issue be closed?
