### ISSUE TITLE
FLAC + CUE

### ISSUE THREAD

**Issue by ElektroQuark** [gavinbenda/platinum-md#58]
Hi,

I have my audio collection as full album FLAC file and a cue sheet.
Now, Platinum-MD reads folder and only finds 1 sound file (the full album).
Is it possible to detect the CUE file and separate each audio track as it should be?
Thank you in advance.

**Comment by gavinbenda** [comment]
This is getting pretty specific, but can see how it would be useful. I'd maaaybe suggest this is something that should be done by another app (split the file up that is). Perhaps this might work? http://flacon.github.io/

**Comment by ElektroQuark** [comment]
I do use another software to do it, but I think it's a basic feature for Platinum-MD. Just my opinion. Of course it's only a suggestion.
Thank you for your work.

**Comment by deenine** [comment]
Please provided process/tools to create an album as a single flac with cue file, to allow for testing.

**Comment by ElektroQuark** [comment]
Hi,

Try this:

http://www.anyburn.com/tutorials/rip-cd-to-flac.htm

**Comment by Shadester** [comment]
Looks like shnsplit can be used for this: https://coderwall.com/p/6ydyoq/how-to-split-flac-files-by-cue-and-convert-to-alac-on-mac-os-x:
```
brew install cuetools flac ffmpeg shntool
shnsplit -o flac -f file.cue file.flac
cuetag file.cue split-track*.flac
```
Although I'm not sure how the windows port would handle this.

**Comment by Shadester** [comment]
There's a win binary for shnsplit here: http://shnutils.freeshell.org/shntool/dist/win32/shntool-3.0.10.zip
cuetag is a shell script in the cuetools package, it will tag the split-track with tags from the cue file.
