### ISSUE TITLE
Conversion to wav will (probably) fail if source is read only filesystem

### ISSUE THREAD

**Issue by deenine** [gavinbenda/platinum-md#64]
In the wav creation stage before transfer to MD, the input media is converted to wav in a subdir of the source directory. This assumes the source directory is writeable - i think this will fail if it is read only.

Use `os.tmpdir() + 'pmd-tmp'` instead?

**Comment by gavinbenda** [comment]
It's a good point, I'm not sure it's super-common to have a read-only file system, but your recommendation makes sense!

**Comment by deenine** [comment]
The obvious case is where someone's music collection is on a read only network share. I am guessing that not many people do this, because no-one has complained :)

**Comment by maverickmatt** [comment]
> The obvious case is where someone's music collection is on a read only network share. I am guessing that not many people do this, because no-one has complained :)

I just encountered this scenario. I'm running a dual-boot hackintosh on a Windows machine, and my music is on the Windows drive. I vaguely remembered this issue/enhancement when I saw the errors in the console. TMP probably makes the most sense - but I see Gavin's point about space. I don't know what's typical on a Mac, but I'd not expect a problem on most Windows machines.

**Comment by Shadester** [comment]
This should be fixed with the #83 that was merged in just now.

**Comment by deenine** [comment]
thanks @Shadester

**Comment by Shadester** [comment]
This ticket can be closed.

**Comment by gavinbenda** [comment]
Nice work! Thanks!
