### ISSUE TITLE
Stop transfering when disc is full

### ISSUE THREAD

**Issue by deenine** [gavinbenda/platinum-md#66]
It would be cool if platinum-MD stopped trying to transfer tracks to the device when the disc is full

**Comment by Invictaz** [comment]
I don't think there is such an option, same in Web Minidisc from @cybercase

**Comment by deenine** [comment]
It would be fairly simple to add. 

Everytime a track is transfered to the device, readNetMd() is called:
```
bus.$on('track-sent', () => {
      this.readNetMd()
    })
```

So therefore, everytime a track is transfered, platinum-md knows the remaining time available on the disc, so add a check prior to starting to convert that remaining time > next track to transfer.

**Comment by Shadester** [comment]
Can this be closed now?
