### ISSUE TITLE
can add sharp DR80 support?

### ISSUE THREAD

**Issue by franciske** [gavinbenda/platinum-md#68]
current version does not support sharp DR80, 

we can modify the disk name, but transfer music failed,

**Comment by Invictaz** [comment]
There is this commit that @gavinbenda might not have included yet in the new builds
See #56 and https://github.com/vuori/linux-minidisc/pull/8

**Comment by gavinbenda** [comment]
Next release is pretty close, so will get you to re-test then - hopefully the new changes means it will work with your Sharp.

**Comment by franciske** [comment]
still waiting for new release, look forward  to work with my sharp.  Thank you in advanced.

**Comment by gavinbenda** [comment]
The new release should support it now, be interested for someone to confirm it does.

**Comment by franciske** [comment]
I confirm myself it works fine with Sharp DR80, Thank you

**Comment by gavinbenda** [comment]
Awesome - thanks for testing! Will close this one off.
