### ISSUE TITLE
OSX 10.12.6 support

### ISSUE THREAD

**Issue by Sprunklez** [gavinbenda/platinum-md#69]
First of all thanks for the great work! Can support for OSX 10.12.6 be made available?

**Comment by Invictaz** [comment]
I'm hoping even support for 10.11 as I cannot update...

**Comment by deenine** [comment]
@Sprunklez @Invictaz what part of installing this on 10.11/10.12 fails? Is it the `brew install....` stage?

**Comment by Pogo9** [comment]
Just wanted to add to this, on 10.12.6, i can install platinum md, but the dependencies fail to install.  At the terminal prompt, brew install fails to run with a response of '-bash brew: command not found'

any solution would be welcomed.  enjoying the prospect of using my minidisc systems on a mac

**Comment by gavinbenda** [comment]
> Just wanted to add to this, on 10.12.6, i can install platinum md, but the dependencies fail to install. At the terminal prompt, brew install fails to run with a response of '-bash brew: command not found'

It should try and install homebrew first - are there any errors from that process?
Otherwise you can try and install homebrew manually by copy-pasting the following into the terminal prompt:

`/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`

**Comment by Pogo9** [comment]
Thanks for the prompt response, Gavin.  Following your lead, i was able to get further but still hit a roadblock.  This time, after installing homebrew manually, i was able to download and start the brew install, but was greeted with this

🍺  /usr/local/Cellar/pkg-config/0.29.2_3: 11 files, 628.7KB, built in 1 minute 25 seconds
qt@5: A full installation of Xcode.app is required to compile
this software. Installing just the Command Line Tools is not sufficient.

Xcode can be installed from the App Store.
Error: An unsatisfied requirement failed this build.

so close!  thanks for your help

**Comment by gavinbenda** [comment]
> Thanks for the prompt response, Gavin. Following your lead, i was able to get further but still hit a roadblock. This time, after installing homebrew manually, i was able to download and start the brew install, but was greeted with this
> 
> 🍺 /usr/local/Cellar/pkg-config/0.29.2_3: 11 files, 628.7KB, built in 1 minute 25 seconds
> qt@5: A full installation of Xcode.app is required to compile
> this software. Installing just the Command Line Tools is not sufficient.
> 
> Xcode can be installed from the App Store.
> Error: An unsatisfied requirement failed this build.
> 
> so close! thanks for your help

You might be able to try opening Platinum-MD again now, and if all goes well, it might be able to install everything else for you, providing it now detects brew as being installed.

If not, you might have reminded me that Qt isn't really needed for running the app, so the packages really could be just:
`brew install libid3tag libtag glib libusb libusb-compat libgcrypt ffmpeg json-c`

**Comment by Pogo9** [comment]
tried reopening but it still stalls. 

for the sake of trying, i booted up my macbook air running 10.14.16, and got the same response of brew not being detected.  I haven't attempted the manual install on it yet. i've got a windows 10 laptop i can attempt it on, and see what occurs.

**Comment by Shadester** [comment]
You did install Xcode from App Store, since it asked for it there, right?

**Comment by gavinbenda** [comment]
> tried reopening but it still stalls.
> 
> for the sake of trying, i booted up my macbook air running 10.14.16, and got the same response of brew not being detected. I haven't attempted the manual install on it yet. i've got a windows 10 laptop i can attempt it on, and see what occurs.

If you manually installed homebrew successfully with no errors (type `brew -v` in the terminal will confirm it's installed), it should also show within Platinum-MD as installed, and it should then be able to install everything it needs (using the `Click Here to Install Now` button in the troubleshooter within Platinum-MD).

**Comment by Pogo9** [comment]
ok, so the stalls is basically where it is telling me that a full version of xcode is necessary to compile the software.  (i've looked for a copy of xcode, but cannot locate one that is compatible with os 10.12.6.  I'm downloading a version that is compatible with the mba that has mojave installed on it.  will give that a try tomorrow.)

brew is seen as installed, and i verified it with the -v command.  

i'm attempting to reinstall pkg-config, to see if that has any different outcome

**Comment by Pogo9** [comment]
Just wanted to update my progress.  On mojave, i was able to install a copy of xcode, and this resulted in the ability to install the required libraries via the troubleshooter gui.  I was able to pull a track off a hi-md disc, so it looks good to go.  

Thanks for your assistance, and for making this awesome platform!

**Comment by gavinbenda** [comment]
Awesome - good to hear you got it working, I guess older versions of OSX require some further build tools with Brew.
