### ISSUE TITLE
Transfer ATRAC SP straight to device without reencode

### ISSUE THREAD

**Issue by Invictaz** [gavinbenda/platinum-md#7]
Hi,

I saw that ATRAC data is re-encoded to PCM by the device. But according to this script the raw AEA files can be transferred to the device.

Can you enlighten a bit more about it?

https://raw.githubusercontent.com/vuori/linux-minidisc/master/netmd/downloadhack.py

**Comment by gavinbenda** [comment]
I believe the terminology Sony (and some of these scripts use) is a bit confusing - that script is for "uploading" a track from your MZ-RH1 to your computer.

**Comment by Invictaz** [comment]
No uploading is their PC to MD.

**Comment by gavinbenda** [comment]
Please reference this function which is called by upload.py
https://github.com/AlexanderS/linux-minidisc/blob/master/netmd/libnetmd.py#L914

```
Digitaly dump a track to file.
This is only available on MZ-RH1.
track (int)
  Track to extract.
outfile_name (str)
  Path of file to save extracted data in.
```

**Comment by Invictaz** [comment]
My mistake it should have been "downloadhack.py"

https://raw.githubusercontent.com/vuori/linux-minidisc/master/netmd/downloadhack.py

I was confused with the upload and download. Upload in my book is from device to pc, download is pc to device. 

https://wiki.physik.fu-berlin.de/linux-minidisc/doku.php?id=netmdpython

See under "downloadhack.py - download tracks to NetMD (buggy)"

Although it seems only .WAV is supported not .AEA

Can you implement this?

**Comment by gavinbenda** [comment]
Yeah the terminology is the wrong way around, confuses me all the time too!!

https://lists.fu-berlin.de/pipermail/linux-minidisc/2010-July/msg00000.html
Here's some notes on usage (note, this is the version before they implemented unencumbered keys).

```
+# USAGE
+#######
+# first: create an uncompressed 16-bit stereo PCM:
+# ffmpeg -i $audiofile -f s16be test.raw
+#######
```

This is exactly what Platinum-MD does in terms of file format for SP, the only difference might be faster transfer speed, but it also seems to be buggy.

**Comment by Invictaz** [comment]
It seems that there were some fixes not implemented in Glaubitz upstream. Maybe you can implement them?

https://github.com/cwningen/linux-minidisc/pull/4/commits/8a497ff3fa6aaa2709fd0234df674724f1e3df23

and 

https://github.com/vuori/linux-minidisc/commits/feature/netmd-crypto-fix

**Comment by gavinbenda** [comment]
Yep - already using a library implementing those changes in Platinum-MD

**Comment by Invictaz** [comment]
Are those the unencumbered keys you mentioned?

**Comment by gavinbenda** [comment]
Originally for transfers to the NetMD device, it needed Sony's root key, but not anymore. It's actually already in the vuori/linux-minidisc changes - they were merged into master quite a while back, which is what is used here.

So in short, we are able to send ATRAC-encoded LP2 files direct to a NetMD device, or a PCM/WAV file that the device encodes to SP (about 12x speed). SonicStage was only able to send "SP" files as an LP2 quality with an SP wrapper, but I haven't seen anyone implement the ability to send a natively ATRAC-encoded SP file direct in full quality.

**Comment by Invictaz** [comment]
That is weird because according to their official Matrix SP file send should be possible 

![image](https://user-images.githubusercontent.com/20338545/70008198-cbed4100-1572-11ea-8168-ad369a72e8c0.png)

Both YES*3 and YES*5

**Comment by xoudan** [comment]
am i right?
 transfer sp means send pcm/wav data to md device by usb,  like mz-n1/mz-n810, then md device encode the pcm to atrac sp mode.

Use platinum-md,I transfer sp to my mz-n810 successfully!!!! It is great, using about 1/4 time of the music play time

**Comment by gavinbenda** [comment]
> am i right?
> transfer sp means send pcm/wav data to md device by usb, like mz-n1/mz-n810, then md device encode the pcm to atrac sp mode.

Yep - that is correct!

**Comment by xoudan** [comment]
Thanks for your reply
I am a chinese MD Fans,MD can not dispplay chinese correctly.


But,there is a way to show "chinese",And many people use this way 
      :Through a software,name '南极星',transefer the chinese disc/trac name to  Japanese Kanji code, then show the  Japanese Kanji instead of chniese， 
      In mz-rm35 and above remote control 
      it can show Japanese kanji ,which looks like a Chinese word,( Event Most of the true means is defferent with the Chinese True means )




Can platinmun--md add this feature or plugin?  switch to change disc name/track name code to kanji.


I am not a python programer, hardly to read platinum-md code, but I can deliver the code mapping (It is not truly translate,but find a kanji which looks like the "same means" )


Again, platinum-md is a greate soft, 












在 2020-11-24 15:07:49，"Gavin Benda" <notifications@github.com> 写道：

am i right?
transfer sp means send pcm/wav data to md device by usb, like mz-n1/mz-n810, then md device encode the pcm to atrac sp mode.

Yep - that is correct!
