### ISSUE TITLE
Selecting multiple tracks and delete only deletes one track

### ISSUE THREAD

**Issue by Shadester** [gavinbenda/platinum-md#79]
If I select multiple tracks and press the x, it will only delete one of the tracks.

This is for the 1.0.0-RC1.

**Comment by deenine** [comment]
Thats my bad. Previously platinum-md would only let you select one track at a time in the netmd pane, so delete only supports one track. I changed it to multiple select for the rh1-pc transfer functionality, but never got around to making delete do multiple files.

Thinking about this, I think you want to take the list of tracks to delete and iterate through from the last track to the first.

**Comment by Shadester** [comment]
Yeah, I started thinking about this yesterday and tried to implement this, but if you go from first to last, it won't work.. Since the numbering will be off. Might make a fix later today.
