### ISSUE TITLE
ffmpeg command for converting tracks after copy from MD to PC fails due to spaces in filenames

### ISSUE THREAD

**Issue by maverickmatt** [gavinbenda/platinum-md#88]
Copied a HiMD track from NH600D to "Mac" as a test (and it worked - yay! Incidentally, I would love to try with a normal MD mode track, but the Transfer button does not show when I insert a normal MD). The copy succeeded and created .OMA file for Atrac3Plus track.  Conversion to WAV format failed, and after investigating, I saw that there were spaces in the generated filenames of the track copied from MD. I copied the command line from the log to run from a command prompt, and after escaping the spaces in the filename, the conversion was successful. Using quotes would probably be simpler I suppose.

ffmpeg -i /Users/matt/pmd-music/Unknown/001-Rod Stewart - Infatuation.oma -y -ar 44100 -acodec pcm_s16le /Users/matt/pmd-music/Unknown/001-Rod Stewart - Infatuation.wav

ffmpeg -i /Users/matt/pmd-music/Unknown/001-Rod\ Stewart\ -\ Infatuation.oma -y -ar 44100 -acodec pcm_s16le /Users/matt/pmd-music/Unknown/001-Rod\ Stewart\ -\ Infatuation.wav

**Comment by gavinbenda** [comment]
Is this still happening on the newest version (v1.2.0) ?

**Comment by maverickmatt** [comment]
Will test tonight

**Comment by maverickmatt** [comment]
It is working correctly on version 1.2. Thanks
