### ISSUE TITLE
Incompatible with ARM Macs due to how it searches for dependencies

### ISSUE THREAD

**Issue by ticky** [gavinbenda/platinum-md#90]
Homebrew doesn't install to `/usr/local/bin` on the new M1 Macs, which means platinum-md can't find any of the executables it expects:

<img width="387" alt="image" src="https://user-images.githubusercontent.com/282113/110890056-2613a080-82a4-11eb-9828-878cd2da858d.png">

The same executables would be available under `/opt/homebrew/bin` on these Macs.

**Comment by gavinbenda** [comment]
That super useful to know - thanks! I will try another approach to try just find the local path - it probably was a slight hack if I'm honest 🤨

**Comment by ticky** [comment]
That's all good! It's a weird new world out there :)

While I'd normally recommend using the `PATH`, in this case I don't think there's a guarantee that it'll be present for the app itself - it's dependent on the user's shell configuration and that isn't processed for GUI applications. I'd maybe suggest adding `/opt/homebrew/bin` and `/usr/local/bin` to the front of the `PATH` variable, and searching for the things you're after in that list.

**Comment by gavinbenda** [comment]
Yep you're exactly right there - there's a path-fix package that may help with this I think.

**Comment by Shadester** [comment]
And this is for Brew 3.0.0?

**Comment by ticky** [comment]
Brew 3.0 is the first that supported ARM Macs fully, but it doesn't change the installation path on Intel Macs, so it's specific to Brew on ARM Macs.

**Comment by AsahiKou** [comment]
Hi, my M1 also has the same problem, it needs to read files under the path ``/opt/homebrew/Cellar``.

**Comment by gavinbenda** [comment]
I think this should be fixed in the latest release (fingers crossed, haven't got an M1 to test on!)

**Comment by ticky** [comment]
It's finding everything on mine! :)

<img width="544" alt="image" src="https://user-images.githubusercontent.com/282113/117917008-1e20ae80-b29d-11eb-92aa-8810e5f5f5a2.png">
