### ISSUE TITLE
Selecting and playing specific tracks doesn't work properly

### ISSUE THREAD

**Issue by Argo707** [gavinbenda/platinum-md#93]
I encountered an issue when I want to select and play a specific Song over the app.
Lets say I have a MD with 30 songs in my player, the first 10 songs work and play fine, but the next 10 tracks just play random tracks on the disc. Tracks 21 - 30 then just won't do anything when selected. Is this a known issue? I'm using an MZ-N707

**Comment by gavinbenda** [comment]
This is be fixed in the new version (released for OSX only at the moment).
https://github.com/gavinbenda/linux-minidisc/commit/fd8ed955b37e938283af302f41fef15a6493d4ea

**Comment by Argo707** [comment]
Awesome, that's great to hear. Didn't see the change!
