### ISSUE TITLE
When to update the Windows version?

### ISSUE THREAD

**Issue by icm2203** [gavinbenda/platinum-md#95]
Need Windows version very much

**Comment by Invictaz** [comment]
Yeah me too. Where is the 1.10 version :)

**Comment by gavinbenda** [comment]
Windows version has been released!

**Comment by Dekko62** [comment]
Well done Gavin!, this looks great. Is there any chance you could incorporate adding folders?, i.e. picking a folder to transfer with subfolders in it - not just the files within a folder?. Anyway solid work done on this.

**Comment by gavinbenda** [comment]
> Well done Gavin!, this looks great. Is there any chance you could incorporate adding folders?, i.e. picking a folder to transfer with subfolders in it - not just the files within a folder?. Anyway solid work done on this.

Thanks for the feedback! The file browser is a hard one, but could be an option to search 'recursively' - it just wouldn't be very nice for people who have huge collections. I am considering the option to open an M3U playlist file though.

**Comment by icm2203** [comment]
> Windows版本已经发布！

Thank you very much, very satisfied.

**Comment by Dekko62** [comment]
Gavin, having trouble writing to a HI-MD disc, not sure if it's a TOC issue. All tracks selected transfer to the disc, and when finished display correctly on the unit display but then get the message 'cannot play'. I have tried it on 2 HI-MD units with the same results. Any ideas?.

**Comment by gavinbenda** [comment]
> Gavin, having trouble writing to a HI-MD disc, not sure if it's a TOC issue. All tracks selected transfer to the disc, and when finished display correctly on the unit display but then get the message 'cannot play'. I have tried it on 2 HI-MD units with the same results. Any ideas?.

I might have seen this same behavior with Hi-MD devices that don't support MP3 mode. There's only a couple that do support it. Regular Hi-MD transfer mode is not supported yet.

**Comment by Dekko62** [comment]
Update: have tried v1.2 with a number of HI-MD units, namely 1) Sony MZ-NH700 2) Sony MZ-NHF800 3) Sony MZ-RH10 4) 
Sony MZ-NH1 5) Sony MZ-RH1. 
Results: MZ-NH700/800 do not work with WAV/FLAC/MP3. RH10 works with WAV, does not work with FLAC/MP3. NH1 works with WAV, does not work with FLAC/MP3. RH1 works with WAV/MP3, does not work with FLAC (RH1 transfer back from unit to PC does not work). Any track with non standard icons (etc. ? on black diamond) results in track transferring but with 0.00 track length. So it looks like the RH1 is the only unit to support MP3.

**Comment by Dekko62** [comment]
Update 2: NH1 does NOT work with WAV/FLAC/MP3 (surprising considering it's such a high spec unit). RH1 works with ALL formats - WAV/FLAC/MP3. Cannot tell if RH1 transfers in PCM properly as the transferred file icon shows MP3 (AEA/AT3 no audio conversion chosen in platinum and disc formatted to PCM). Realisation: all units actually record tracks properly, but cannot play back in any format - apart from the RH1.
